spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  kafka:
    bootstrap-servers: peter-kafka01:9092
    consumer:
      # consumer bootstrap servers? ?? ???? ??
      bootstrap-servers: peter-kafka01:9092

      # ?? ??? Consumer Group Id
      group-id: devbeekei
      # Kafka ??? ?? offset? ???, ??? ?? offset? ? ?? ???? ?? ?? ??? ??? ??
      # latest: ?? ??? ??? ???? offeset reset
      # earliest: ?? ??? ???? offeset reset
      # none: offset ??? ??? Exception ??
      auto-offset-reset: earliest
      # ???? ??? ?, key/value? ????
      # JSON ???? ??? ???? JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      # producer bootstrap servers? ?? ???? ??
      bootstrap-servers: peter-kafka01:9092

      # ???? ?? ?, key/value? ???
      # JSON ???? ?? ???? JsonDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer